FROM cloudfoundry/cflinuxfs4

RUN apt-get update \
    && apt-get install -y \
    build-essential \
    curl \
    libpoppler-dev \ 
    libpoppler-glib-dev \
    poppler-utils \
    software-properties-common \
    s3fs \
    tree \
    wget 

# Copy the zscaler root CA into the container and add it to the list of OpenSSL
# root certificates.
COPY zscaler-root.pem /etc/ssl/certs/zscaler-root.pem
# Rebuild the CA cache. Otherwise the prior step is useless.
RUN c_rehash

# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
#     && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
# RUN apt-get update && apt-get -y install google-chrome-stable

# RUN add-apt-repository ppa:longsleep/golang-backports
# RUN apt-get update \
#     && apt-get install -y \
#     golang-go


WORKDIR /minio
RUN curl https://dl.min.io/client/mc/release/linux-amd64/mc \
    --create-dirs \
    -o /minio/mc
RUN chmod +x /minio/mc

# What about litestream for moving things into/out-of S3?
RUN wget https://github.com/benbjohnson/litestream/releases/download/v0.3.13/litestream-v0.3.13-linux-amd64.deb
RUN dpkg -i litestream-v0.3.13-linux-amd64.deb

WORKDIR /sqlc
RUN wget https://downloads.sqlc.dev/sqlc_1.27.0_linux_amd64.tar.gz \ 
    && tar xvzf sqlc_1.27.0_linux_amd64.tar.gz \
    && chmod 755 sqlc \
    && mv sqlc /bin/sqlc

WORKDIR /go_install
RUN rm -rf /usr/local/go \
    && wget https://go.dev/dl/go1.23.3.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go1.23.3.linux-amd64.tar.gz

WORKDIR /mountpoint
RUN wget https://s3.amazonaws.com/mountpoint-s3-release/latest/x86_64/mount-s3.deb \
    && dpkg -i mount-s3.deb


ENV PATH=$PATH:/usr/local/go/bin:/root/go/bin
RUN go install golang.org/x/tools/cmd/goimports@latest    
RUN go install golang.org/x/tools/cmd/stringer@latest
RUN go install github.com/google/go-jsonnet/cmd/jsonnet@latest
RUN go install github.com/google/go-jsonnet/cmd/jsonnet-lint@latest
RUN go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest
RUN cp /root/go/bin/stringer /usr/local/go/bin/stringer

WORKDIR /golanglint
# binary will be $(go env GOPATH)/bin/golangci-lint
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/go/bin v1.63.4


ENTRYPOINT ["tree /"]