// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package search_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Metadatum struct {
	ID    int32       `json:"id"`
	Col   pgtype.Text `json:"col"`
	Value pgtype.Text `json:"value"`
}

type RawContent struct {
	ID       int64       `json:"id"`
	Domain64 pgtype.Int8 `json:"domain64"`
	Path     pgtype.Text `json:"path"`
	Tag      pgtype.Text `json:"tag"`
	Content  pgtype.Text `json:"content"`
}
