// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package search_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getrawcontent = `-- name: getrawcontent :one
select id, domain64, path, tag, content from raw_content 
where 
  domain64 = $1 
  and
  path = $2
  limit 1
`

type getrawcontentParams struct {
	Domain64 pgtype.Int8 `json:"domain64"`
	Path     pgtype.Text `json:"path"`
}

func (q *Queries) getrawcontent(ctx context.Context, arg getrawcontentParams) (RawContent, error) {
	row := q.db.QueryRow(ctx, getrawcontent, arg.Domain64, arg.Path)
	var i RawContent
	err := row.Scan(
		&i.ID,
		&i.Domain64,
		&i.Path,
		&i.Tag,
		&i.Content,
	)
	return i, err
}
