// Code generated by "stringer -type=FetchStatus"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotPreviouslySeen-0]
	_ = x[DeadlineNotYetReached-1]
	_ = x[DeadlinePassed-2]
	_ = x[NotFound-3]
	_ = x[HallPass-4]
	_ = x[DefaultCase-5]
}

const _FetchStatus_name = "NotPreviouslySeenDeadlineNotYetReachedDeadlinePassedNotFoundHallPassDefaultCase"

var _FetchStatus_index = [...]uint8{0, 17, 38, 52, 60, 68, 79}

func (i FetchStatus) String() string {
	if i < 0 || i >= FetchStatus(len(_FetchStatus_index)-1) {
		return "FetchStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FetchStatus_name[_FetchStatus_index[i]:_FetchStatus_index[i+1]]
}
