// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package work_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ContentType struct {
	ID          int32  `json:"id"`
	ContentType string `json:"content_type"`
}

type Guestbook struct {
	ID            int64            `json:"id"`
	LastModified  pgtype.Timestamp `json:"last_modified"`
	LastFetched   pgtype.Timestamp `json:"last_fetched"`
	NextFetch     pgtype.Timestamp `json:"next_fetch"`
	Scheme        int32            `json:"scheme"`
	Host          int32            `json:"host"`
	ContentType   pgtype.Int4      `json:"content_type"`
	ContentLength int32            `json:"content_length"`
	Path          string           `json:"path"`
}

type Host struct {
	ID        int64            `json:"id"`
	NextFetch pgtype.Timestamp `json:"next_fetch"`
	Domain64  pgtype.Int8      `json:"domain64"`
	Host      pgtype.Text      `json:"host"`
}

type RawContent struct {
	ID          int64       `json:"id"`
	GuestbookID int64       `json:"guestbook_id"`
	Tag         pgtype.Text `json:"tag"`
	Content     string      `json:"content"`
}

type Scheme struct {
	ID     int32  `json:"id"`
	Scheme string `json:"scheme"`
}

type Tag struct {
	ID   int32       `json:"id"`
	Tag  string      `json:"tag"`
	Attr pgtype.Text `json:"attr"`
}

type Tld struct {
	ID  int32  `json:"id"`
	Tld string `json:"tld"`
}
