local hosts = [
  'www.cancer.gov',
  'www.nei.nih.gov',
  'www.nhlbi.nih.gov',
  'www.genome.gov',
  'www.nia.nih.gov',
  'www.niaaa.nih.gov',
  'www.niaid.nih.gov',
  'www.niams.nih.gov',
  'www.nibib.nih.gov',
  'www.nichd.nih.gov',
  'www.nichd.nih.gov',
  'www.nidcr.nih.gov',
  'www.niddk.nih.gov',
  'nida.nih.gov',
  'www.niehs.nih.gov',
  'www.nigms.nih.gov',
  'www.nimh.nih.gov',
  'www.nimhd.nih.gov',
  'www.ninds.nih.gov',
  'www.ninr.nih.gov',
  'www.nlm.nih.gov',
  'www.cc.nih.gov',
  'www.cit.nih.gov',
  'public.csr.nih.go',
  'www.fic.nih.gov',
  'ncats.nih.gov',
  'www.nccih.nih.gov',
];

{
  monthly: [{ scheme: 'https', path: '/', host: h } for h in hosts],
}
